/**
 * Append-only decision log (Phase 3, adopted from OpenMontage).
 *
 * Every meaningful architectural/policy decision (provider selection, runtime
 * fallback, budget tradeoff, model selection, voice selection, approval policy)
 * is recorded here with the options considered and why they were rejected.
 * Makes the system's choices auditable and gives the Control Center a decision
 * rail.
 */
import { z } from 'zod';

export const DECISION_LOG_CATEGORIES = [
  'provider_selection',
  'model_selection',
  'runtime_selection',
  'fallback_decision',
  'budget_tradeoff',
  'voice_selection',
  'approval_policy',
] as const;
export type DecisionLogCategory = (typeof DECISION_LOG_CATEGORIES)[number];

export const decisionLogEntrySchema = z.object({
  id: z.string(),
  contentId: z.string().nullish(),
  stage: z.string().nullish(),
  category: z.enum(DECISION_LOG_CATEGORIES),
  subject: z.string(),
  decision: z.string(),
  optionsConsidered: z.array(z.string()).default([]),
  rejectedBecause: z.array(z.string()).default([]),
  createdAt: z.string(),
});
export type DecisionLogEntry = z.infer<typeof decisionLogEntrySchema>;

/** Inputs for appending a decision (id/timestamp generated by the caller/DB). */
export type DecisionLogInput = Omit<DecisionLogEntry, 'id' | 'createdAt'> &
  Partial<Pick<DecisionLogEntry, 'id' | 'createdAt'>>;
